const SAMPLE_FOOD_DATA = {
  Breakfast: [
    {
      idx: 0,
      Recipe_ID: 283,
      Cuisine: "Indian",
      Recipe_Name: "Ayurvedic Oats Porridge with Nuts",
      Description:
        "A nutritious and warming breakfast porridge made with steel-cut oats, almonds, walnuts, and warming spices. Perfect for balancing Vata dosha and providing sustained energy throughout the morning.",
      Image_URLs: "['https://example.com/oats-porridge.jpg']",
      Keywords: "['Healthy', 'Oats', 'Nuts', 'Warming', 'Vata']",
      Ingredient_Quantities:
        "['1/2 cup', '1 cup', '2 tbsp', '1 tbsp', '1 tsp', '1/2 tsp', '1/4 tsp', '1 tbsp', '1 tsp']",
      Ingredient_Names:
        "['steel-cut oats', 'water', 'almonds', 'walnuts', 'ghee', 'cinnamon', 'cardamom', 'honey', 'vanilla']",
      Calories: "285.4",
      Fat_g: "12.8",
      Saturated_Fat_g: "3.2",
      Cholesterol_mg: "8.1",
      Sodium_mg: "5.2",
      Carbohydrates_g: 38.7,
      Fiber_g: "6.8",
      Sugar_g: 12.4,
      Protein_g: 8.9,
      Instructions:
        "['Soak steel-cut oats in water for 10 minutes.' 'In a saucepan, heat ghee and add cinnamon and cardamom.' 'Add soaked oats and water, bring to boil.' 'Simmer for 15-20 minutes until creamy.' 'Add chopped nuts and honey, mix well.' 'Serve warm with a drizzle of vanilla.']",
      Meal_Category: "Breakfast",
      Dosha: "Vata, Pitta",
      Region: "North",
      Rasas: "Madhura, Katu",
    },
    {
      idx: 1,
      Recipe_ID: 1161,
      Cuisine: "Indian",
      Recipe_Name: "Quinoa Upma with Vegetables",
      Description:
        "A protein-rich breakfast made with quinoa, mixed vegetables, and aromatic spices. This modern take on traditional upma provides complete amino acids and essential nutrients for a healthy start to the day.",
      Image_URLs: "['https://example.com/quinoa-upma.jpg']",
      Keywords: "['Quinoa', 'Vegetables', 'Protein', 'Healthy', 'Gluten-free']",
      Ingredient_Quantities:
        "['1 cup', '2 cups', '1/2 cup', '1/4 cup', '1 tbsp', '1 tsp', '1/2 tsp', '1/4 tsp', '2 tbsp']",
      Ingredient_Names:
        "['quinoa', 'water', 'mixed vegetables', 'onion', 'ghee', 'mustard seeds', 'turmeric', 'salt', 'coriander leaves']",
      Calories: "198.7",
      Fat_g: "4.2",
      Saturated_Fat_g: "1.8",
      Cholesterol_mg: "0.0",
      Sodium_mg: "245.3",
      Carbohydrates_g: 34.8,
      Fiber_g: "4.1",
      Sugar_g: 3.2,
      Protein_g: 7.5,
      Instructions:
        "['Rinse quinoa thoroughly and drain.' 'Heat ghee in a pan and add mustard seeds.' 'When seeds splutter, add chopped onion and sauté.' 'Add mixed vegetables and cook for 2-3 minutes.' 'Add quinoa, water, turmeric, and salt.' 'Cover and cook for 15-20 minutes until quinoa is tender.' 'Garnish with coriander leaves and serve hot.']",
      Meal_Category: "Breakfast",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Lavana, Katu, Tikta",
    },
    {
      idx: 2,
      Recipe_ID: 284,
      Cuisine: "Indian",
      Recipe_Name: "Protein-Rich Moong Dal Chilla",
      Description:
        "A high-protein breakfast pancake made with split moong dal, vegetables, and spices. Rich in essential amino acids and perfect for muscle building and weight management.",
      Image_URLs: "['https://example.com/moong-dal-chilla.jpg']",
      Keywords: "['Protein', 'Dal', 'Pancake', 'Healthy', 'Gluten-free']",
      Ingredient_Quantities:
        "['1 cup', '1/2 cup', '1/4 cup', '1 tbsp', '1 tsp', '1/2 tsp', '1/4 tsp', '2 tbsp']",
      Ingredient_Names:
        "['split moong dal', 'water', 'onion', 'ginger', 'green chilies', 'turmeric', 'salt', 'oil']",
      Calories: "156.8",
      Fat_g: "3.4",
      Saturated_Fat_g: "0.8",
      Cholesterol_mg: "0.0",
      Sodium_mg: "198.5",
      Carbohydrates_g: 22.1,
      Fiber_g: "8.2",
      Sugar_g: 2.1,
      Protein_g: 12.7,
      Instructions:
        "['Soak moong dal for 4-6 hours.' 'Grind dal with water to make smooth batter.' 'Add chopped vegetables and spices.' 'Heat a non-stick pan and pour batter.' 'Cook on both sides until golden brown.' 'Serve hot with chutney.']",
      Meal_Category: "Breakfast",
      Dosha: "Vata, Pitta",
      Region: "North",
      Rasas: "Lavana, Katu",
    },
    {
      idx: 20,
      Recipe_ID: 718,
      Cuisine: "Indian",
      Recipe_Name: "Indians Cookie",
      Description: "Make and share this Indians Cookie recipe from Food.com.",
      Image_URLs: "[]",
      Keywords: "['Dessert', 'Cookie & Brownie', '< 60 Mins']",
      Ingredient_Quantities: "['1⁄2' '1' '1' '2' '2' '1⁄4' '3⁄4' '1']",
      Ingredient_Names:
        "['butter', 'sugar', 'vanilla', 'eggs', 'salt', 'flour', 'walnuts']",
      Calories: "313.7",
      Fat_g: "20.9",
      Saturated_Fat_g: "8.7",
      Cholesterol_mg: "66.7",
      Sodium_mg: "139.3",
      Carbohydrates_g: 30.6,
      Fiber_g: "2.0",
      Sugar_g: 20.5,
      Protein_g: 4.8,
      Instructions:
        "['melt chocolate' 'cream butter and sugar' 'add vanilla' 'add eggs' 'beat' 'stir in melted choclate sift dry ingredients' 'add to creamed mixture' 'add nuts' 'spread evenly in 9x9x13/4 inch greased baking pan' 'bake at 350 degrees for 25 minutes' 'cut into squares or bars.']",
      Meal_Category: "Breakfast",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Madhura, Lavana",
    },
    {
      idx: 30,
      Recipe_ID: 567,
      Cuisine: "Indian",
      Recipe_Name: " Baked Potato Cakes-Cooking Light",
      Description:
        "Very yummy spicy potato cakes. Perfect for grilled chicken, pork, fish, even steak! Feel free to play around with spices to your taste! Taken from the cooking light August 2007 issue.",
      Image_URLs: "[]",
      Keywords:
        "['Vegetable', 'Asian', 'Indian', 'Spicy', '< 60 Mins', 'Easy']",
      Ingredient_Quantities:
        "['1' '1⁄2' '1⁄2' '1' '4 1⁄2' '2' '2' '1⁄4' '1⁄4' '1' None '5' '2' '1' '1']",
      Ingredient_Names:
        "['canola oil', 'mustard seeds', 'cumin seed', 'kosher salt', 'baking potatoes', 'fresh parsley', 'canola oil', 'ground turmeric', 'fresh ground pepper', 'light sour cream', 'fresh cilantro', 'garlic', 'onion powder']",
      Calories: "102.8",
      Fat_g: "4.2",
      Saturated_Fat_g: "0.7",
      Cholesterol_mg: "2.5",
      Sodium_mg: "183.3",
      Carbohydrates_g: 15.2,
      Fiber_g: "1.4",
      Sugar_g: 0.7,
      Protein_g: 1.7,
      Instructions:
        "['Preheat oven to 400°F.' 'Heat 1 teaspoon oil in a small skillet over medium heat. Add mustard and cumin seeds to pan; cook 2 minutes or until mustard seeds pop, stirring constantly. Remove from heat.' 'Place spice mixture and salt in a mortar; crush seeds with a pestle and set aside.' 'Gently squeeze potato to remove excess moisture.' 'Combine potato, spice mixture, parsley, 2 tablespoons of oil, tumeric, and peppers in a large bowl, and whatever other spices you may add.' 'Divide mixture evenly into 10 portions, about 1/3 cup. Place on baking sheet coated with cooking spray. Flatten to 1/2 inch thickness.' 'Bake at 400°F for 16 minutes or until golden. Turn over; bake an additional 5 minutes.' 'Serve with sour cream.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Amla, Lavana, Katu",
    },
    {
      idx: 33,
      Recipe_ID: 571,
      Cuisine: "Indian",
      Recipe_Name: "Americanized Daal Baati",
      Description:
        "Make and share this Americanized Daal Baati (Indian-Rajasthan) recipe from Food.com.",
      Image_URLs: "[]",
      Keywords: "['Asian', 'Indian', '< 30 Mins']",
      Ingredient_Quantities:
        "['2' '1' '4' '1⁄2' '3⁄4' '1' '1⁄2' '1 -2' '1⁄2' '1' '1⁄4' '1' '1⁄4' '1⁄2' '1' '1⁄2' '1' '1⁄4' '4' None]",
      Ingredient_Names:
        "['wheat flour', 'baking powder', 'salt', 'milk', 'channa dal', 'ghee', 'garam masala', 'red chili powder', 'haldi powder', 'haldi powder', 'lemon', 'gingerroot', 'cumin seed', 'mustard seeds', 'water', 'salt']",
      Calories: "247.0",
      Fat_g: "5.3",
      Saturated_Fat_g: "2.3",
      Cholesterol_mg: "9.7",
      Sodium_mg: "465.2",
      Carbohydrates_g: 43.2,
      Fiber_g: "8.1",
      Sugar_g: 2,
      Protein_g: 10.1,
      Instructions:
        "['BAATI (AMERICAN DROP DUMPLINGS).' '=================.' 'Mix flour, sooji, baking powder, and salt in a mixing bowl. Add milk and stir to make a soft dough. Add more milk or flour, depending on if dough is too thin or too stiff.' 'DAAL.' '=================.' 'Wash both dals together. Add 2 cups water, a pinch of turmeric and cook dal in pressure cooker 1 whistle and low heat for about 15 min;let pressure release naturally.' 'Mix 1/2 tbs Garam masala, 1 tsp Red chilli powder, 1/4 tsp Haldi (turmeric) powder, 1/4 tsp Dhania pwdr(coriander)in 1/2 cup water to make thin paste. Put ghee in a pan and heat.' 'Splutter 1 tsp cumin seeds, 1/2 tsp mustard seeds, & 1/4 tsp coriander seeds. Add ginger and the paste of spice powders. Fry for a minute, then mix it into the dal. Add 2 cups of water, salt and stir well. Drop dumpling dough into dal and simmer for 15 minutes without removing cover. Add lemon juice. Garnish with chopped coriander & serve.']",
      Meal_Category: "Breakfast",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Amla, Lavana, Katu",
    },
    {
      idx: 34,
      Recipe_ID: 626,
      Cuisine: "Indian",
      Recipe_Name: "Scrambled Eggs",
      Description:
        "Lovely spicey alternative to the traditional scrambled egg. Will wake you up in the morning for sure.",
      Image_URLs: "[]",
      Keywords: "['Asian', 'Indian', '< 15 Mins', 'Beginner Cook', 'Easy']",
      Ingredient_Quantities: "['3' '1' '1' '1' '1⁄2' '2' '1']",
      Ingredient_Names:
        "['eggs', 'turmeric powder', 'salt', 'pepper', 'onion', 'green chilies']",
      Calories: "367.7",
      Fat_g: "26.4",
      Saturated_Fat_g: "5.9",
      Cholesterol_mg: "491.0",
      Sodium_mg: "351.0",
      Carbohydrates_g: 14.8,
      Fiber_g: "2.3",
      Sugar_g: 7.4,
      Protein_g: 19,
      Instructions:
        "['Beat the eggs, chilli flakes and pepper together.' 'Gently fry the onion in the vegetable oil until the onion becomes translucent.' 'Add in the turmeric powder and salt and stir fry for one minute to get rid of the powdery feel.' 'Add the egg mixture into the pan and stir vigorously until you get the scrambled egg texture.' 'Serve on warm toast.' 'Geogeous!']",
      Meal_Category: "Breakfast",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Lavana, Katu",
    },
    {
      idx: 38,
      Recipe_ID: 560,
      Cuisine: "Indian",
      Recipe_Name: " Coffee",
      Description:
        "This recipe contains spices common to chai, yet is quite unique. A real eye-opener to kick start your morning.",
      Image_URLs: "[' ' ' ' ' ' ' ' ' ' ']",
      Keywords:
        "['Breakfast', 'Asian', 'Indian', 'Spicy', 'Sweet', 'Brunch', '< 15 Mins', 'Easy']",
      Ingredient_Quantities: "['1 1⁄4' '4' '1' '1' '1' '2' '1' '2']",
      Ingredient_Names:
        "['water', 'cardamom pods', 'cinnamon stick', 'nutmeg', 'clove', 'brewed coffee', 'milk', 'sugar']",
      Calories: "64.8",
      Fat_g: "2.3",
      Saturated_Fat_g: "1.4",
      Cholesterol_mg: "8.5",
      Sodium_mg: "34.5",
      Carbohydrates_g: 9.2,
      Fiber_g: "0.0",
      Sugar_g: 6.3,
      Protein_g: 2.1,
      Instructions:
        "['In a medium-size pot, bring water to a boil.' 'Stir in the spices, cover, and simmer over low heat for 5 minutes.' 'Stir in the pre-brewed coffee.' 'Meanwhile, in a saucepan, heat milk until almost boiling.' 'Strain the coffee through a fine mesh strainer covered with cheesecloth into the milk.' 'Add sweetener, stir, and serve in mugs.']",
      Meal_Category: "Breakfast",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Madhura, Amla, Katu",
    },
    {
      idx: 49,
      Recipe_ID: 755,
      Cuisine: "Indian",
      Recipe_Name: "Chai Latte Muffins",
      Description:
        "Make and share this Indian Chai Latte Muffins recipe from Food.com.",
      Image_URLs: "['",
      Keywords: "['Breakfast', '< 30 Mins', 'Oven']",
      Ingredient_Quantities:
        "['2' '1⁄2' '2 1⁄2' '1⁄2' '1⁄2' '1⁄4' '1⁄2' '1' '1⁄2' '1' '1' '1' '4' '1⁄4' '2']",
      Ingredient_Names:
        "['all-purpose flour', 'dark brown sugar', 'baking powder', 'ground ginger', 'ground cardamom', 'ground allspice', 'salt', 'buttermilk', 'butter', 'egg', 'vanilla', 'white chocolate chips', 'cream cheese', 'vanilla', 'sugar']",
      Calories: "312.3",
      Fat_g: "16.3",
      Saturated_Fat_g: "10.0",
      Cholesterol_mg: "51.2",
      Sodium_mg: "299.1",
      Carbohydrates_g: 37,
      Fiber_g: "0.6",
      Sugar_g: 20.4,
      Protein_g: 5,
      Instructions:
        "['Preheat oven to 375.' 'Grease 12 muffin cups or use butter-flavored spray.' 'Mix all dry ingredients together, add milk, melted butter, egg, and vanilla, mix well. Stir in white chocolate chips.' 'Spoon into 12 muffin tins.' 'Mix cream cheese, vanilla and sugar together until smooth. Using the back of a spoon make an indentation in the top of each muffin and add a heaping teaspoon of cream cheese mixture into the indentation.' 'Bake at 375 for 18 to 25 minutes, until edges of muffins begin to turn golden brown. Test with toothpick in side of muffin away from cream cheese filling. Remove and cool.' 'If using mini-muffin cups, bake 15-18 minutes.']",
      Meal_Category: "Breakfast",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Lavana",
    },
    {
      idx: 28,
      Recipe_ID: 103,
      Cuisine: "Indian",
      Recipe_Name: "Baklava - An Milk Sweet In Sugar Syrup",
      Description:
        "Make and share this Baklava - An Indian Milk Sweet In Sugar Syrup recipe from Food.com.",
      Image_URLs: "[]",
      Keywords:
        "['Fruit', 'Nuts', 'Asian', 'Indian', '< 60 Mins', 'Stove Top']",
      Ingredient_Quantities: "['1' '1⁄2' '200' '500' '1' '2' '4' '1' None]",
      Ingredient_Names:
        "['milk', 'semolina', 'butter', 'sugar', 'water', 'vanilla essence']",
      Calories: "553.4",
      Fat_g: "22.9",
      Saturated_Fat_g: "11.3",
      Cholesterol_mg: "47.7",
      Sodium_mg: "216.1",
      Carbohydrates_g: 79,
      Fiber_g: "2.7",
      Sugar_g: 42.2,
      Protein_g: 10.2,
      Instructions:
        "['Heat a pan on medium flame.' 'Add butter.' 'Once it melts, add vermicelli to it.' 'Stir-fry it until it turns golden brown.' 'Remove from heat.' 'In an oven proof tray, spread half of the fried vermicelli.' 'In another pan, add the milk, essence and semolina.' 'Mix it until the mixture is like a thick syrup.' 'Add the chopped nuts.' 'Cool it for 5 minutes.' 'Pour it over the vermicelli spread in the tray.' 'Allow it to set.' 'Spread the rest of the vermicelli over it.' 'Bake in an oven for 10-12 minutes or till the top browns.' 'In the pan, add the sugar, water and orange rind with a little vanilla essence.' 'When the syrup boils, cool it.' 'Pour it over the vermicelli on top.' 'Press on the sides so that the syrup is absorbed inside the sweet.' 'Cut into equal sized squares.' 'Serve warm.' 'If it remains, you can refrigerate it for 5 days, but make sure you warm it up in the oven before serving.' 'It has to be had\"hot\" to be relished!']",
      Meal_Category: "Breakfast",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Madhura",
    },
  ],
  Lunch: [
    {
      idx: 1,
      Recipe_ID: 284,
      Cuisine: "Indian",
      Recipe_Name: "Quinoa Buddha Bowl with Roasted Vegetables",
      Description:
        "A nutrient-dense lunch bowl featuring quinoa, roasted seasonal vegetables, chickpeas, and a tahini dressing. Packed with plant-based protein, fiber, and essential vitamins.",
      Image_URLs: "['https://example.com/quinoa-buddha-bowl.jpg']",
      Keywords: "['Quinoa', 'Vegetables', 'Protein', 'Healthy', 'Vegan']",
      Ingredient_Quantities:
        "['1 cup', '2 cups', '1 cup', '1/2 cup', '1/4 cup', '2 tbsp', '1 tbsp', '1 tsp', '1/2 tsp']",
      Ingredient_Names:
        "['quinoa', 'mixed vegetables', 'chickpeas', 'avocado', 'tahini', 'lemon juice', 'olive oil', 'cumin', 'salt']",
      Calories: "387.2",
      Fat_g: "15.8",
      Saturated_Fat_g: "2.1",
      Cholesterol_mg: "0.0",
      Sodium_mg: "234.5",
      Carbohydrates_g: 52.3,
      Fiber_g: "12.7",
      Sugar_g: 8.9,
      Protein_g: "16.4",
      Instructions:
        "['Cook quinoa according to package instructions.' 'Roast mixed vegetables with olive oil and spices.' 'Prepare tahini dressing with lemon juice.' 'Arrange quinoa, vegetables, and chickpeas in bowl.' 'Top with avocado and drizzle with dressing.' 'Serve immediately.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Pitta",
      Region: "West",
      Rasas: "Madhura, Lavana, Katu",
    },
    {
      idx: 0,
      Recipe_ID: 1019,
      Cuisine: "Indian",
      Recipe_Name: "Boka Dushi",
      Description:
        "Ketjap manis (see my fav recipe #480813), the ancestor of modern ketchup, is a thick, sweet soy sauce; you can substitute equal parts soy sauce and molasses. Sambal oelek is a fiery paste made of red peppers. Look for both in Asian markets. From Cooking Light.",
      Image_URLs: "[]",
      Keywords:
        "['Chicken', 'Poultry', 'Meat', 'Indian', 'Spicy', '< 60 Mins']",
      Ingredient_Quantities:
        "['1⁄4' '1' '1' '2' '1' '1⁄2' '1 1⁄2' None '1⁄3' '3' '1⁄2' '2' '2' '1' '1' '1' '1' '1' '1']",
      Ingredient_Names:
        "['ketjap manis', 'fresh lime juice', 'ground cumin', 'fresh ginger', 'sambal oelek', 'ground turmeric', 'boneless skinless chicken breasts', 'creamy peanut butter', 'tomatoes', 'green onions', 'fresh cilantro', 'fish sauce', 'fresh lime juice', 'fresh ginger', 'honey', 'garlic clove']",
      Calories: "189.3",
      Fat_g: "7.1",
      Saturated_Fat_g: "1.5",
      Cholesterol_mg: "72.6",
      Sodium_mg: "406.2",
      Carbohydrates_g: 4.4,
      Fiber_g: "0.9",
      Sugar_g: 2.4,
      Protein_g: 26.6,
      Instructions:
        "['Combine first 7 ingredients in a large zip-top plastic bag; seal and marinate in refrigerator 30 minutes.' 'Prepare grill.' 'Remove chicken from bag and discard marinade. Thread chicken strips onto 18 (8-inch) skewers (soaked if wooden).' 'Place kebabs on grill rack coated with vegetable oil; grill 2 minutes on each side or until done. Serve with prepared Peanut Sauce.' 'To make the Peanut Sauce: Combine broth and peanut butter in a small saucepan; cook over low heat 5 minutes or until smooth, stirring with a whisk. Pour peanut butter mixture into a bowl; stir in the remaining ingredients. Serve at room temperature.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West Indian",
      Rasas: "Madhura, Amla, Katu",
    },
    {
      idx: 1,
      Recipe_ID: 1121,
      Cuisine: "Indian",
      Recipe_Name: "West Rice And Beans",
      Description:
        "Serve this Caribbean-influenced dish with some crusty bread and an avocado orange salad. Recipe is from Bon Appetit.",
      Image_URLs: "[]",
      Keywords:
        "['Onions', 'Beans', 'Vegetable', 'Caribbean', 'Weeknight', '< 60 Mins', 'Easy']",
      Ingredient_Quantities: "['2 1⁄2' '1' '1' '1' '1' '1⁄4' '3⁄4' '1']",
      Ingredient_Names:
        "['vegetable broth', 'kidney beans', 'light coconut milk', 'dried thyme', 'ground allspice', 'medium-grain white rice', 'green onion']",
      Calories: "461.2",
      Fat_g: "1.9",
      Saturated_Fat_g: "0.5",
      Cholesterol_mg: "0.0",
      Sodium_mg: "638.8",
      Carbohydrates_g: 93.3,
      Fiber_g: "14.0",
      Sugar_g: 5.2,
      Protein_g: 16.9,
      Instructions:
        "['Combine 2 cups broth, beans, coconut milk, jalapeno pepper, thyme, and allspice in a heavy large saucepan. Bring to a boil over medium-high heat. Stir in rice. Reduce heat to medium-low and simmer uncovered until most of liquid is absorbed and rice is almost tender, stirring often, about 20 minutes.' 'Mix 3/4 cup green onions into rice. Continue to simmer until rice is very tender and mixture is creamy, adding more broth by 1/4 cupfuls if mixture seems dry and stirring often, about 5 minutes longer. Season to taste with salt and pepper. Transfer to serving bowl. Sprinkle with remaining 1/4 cup green onions.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West Indian",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 2,
      Recipe_ID: 1141,
      Cuisine: "Indian",
      Recipe_Name: "Creamy North Fish Curry",
      Description:
        "This recipe is a slightly modified version of Anjum Anand's Creamy Tomato Fish Curry. Posting in order to review.",
      Image_URLs: "[]",
      Keywords: "['Tilapia', 'Indian', '< 60 Mins', 'Easy']",
      Ingredient_Quantities:
        "['1' '3' '1⁄2' '1⁄2' '4' '1⁄2' '2' '1⁄2' '2 1⁄2' None None '1⁄2' '3⁄4' '1⁄4' '1' '2 -3' None]",
      Ingredient_Names:
        "['mustard seeds', 'small onion', 'garlic cloves', 'ginger', 'hot green chili peppers', 'turmeric', 'tomato paste', 'water', 'cumin powder', 'coriander powder', 'garam masala', 'white vinegar', 'coconut cream', 'coriander leaves']",
      Calories: "378.9",
      Fat_g: "25.2",
      Saturated_Fat_g: "6.0",
      Cholesterol_mg: "37.5",
      Sodium_mg: "211.1",
      Carbohydrates_g: 23.2,
      Fiber_g: "2.3",
      Sugar_g: 15.4,
      Protein_g: 18.1,
      Instructions:
        "['Heat oil in a nonstick saucepan. Add mustard seeds. When mustard seeds start to splatter, add onion and whole green chilies. Cook on a low flame until onions are golden brown.' 'Blend ginger and garlic with tomato paste and around 1/2 cup water until smooth.' 'Add to the pan with the spices and salt and cook on medium-high until oil starts to appear on the surface. Lower heat as necessary as the mixture reduces. Taste mixture and add seasoning as necessary.' 'Add some water, vinegar and coconut cream, and boil until creamy (3-4 minutes). Taste and adjust seasoning if necessary.' 'Add fish. Cook for 5-6 minutes, turning as necessary.' 'Serve hot with rice or naan.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West Bengal",
      Rasas: "Katu",
    },
    {
      idx: 4,
      Recipe_ID: 745,
      Cuisine: "Indian",
      Recipe_Name: "South Fish Curry",
      Description:
        "It's a staple in Kerala - the southernmost state of India. It's spicy and tangy and is excellent with rice.",
      Image_URLs: "['",
      Keywords: "['< 60 Mins']",
      Ingredient_Quantities:
        "['1' '3' '1' '1' '1' '1 1⁄2' '3' '1⁄2' '2' '1' '1' None]",
      Ingredient_Names:
        "['curry leaf', 'shallot', 'tamarind pulp', 'red chili powder', 'turmeric powder', 'coriander powder', 'fenugreek seeds', 'mustard seeds', 'asafoetida powder']",
      Calories: "49.7",
      Fat_g: "4.0",
      Saturated_Fat_g: "0.6",
      Cholesterol_mg: "0.0",
      Sodium_mg: "21.9",
      Carbohydrates_g: 3.5,
      Fiber_g: "1.1",
      Sugar_g: 0.6,
      Protein_g: 0.9,
      Instructions:
        "['Wash and clean the fish.' 'Mix the chili powder, turmeric and coriander powder with a few drops of water to make a thick paste.' 'In a shallow pan, heat the oil.' 'Add the mustard seeds and the fenugreek seeds and sauté till they splutter.' 'Add the shallots and fry till golden brown.' 'Add the spices paste and fry for 2 minutes.' 'Add 1 cup water and tamarind and bring to boil.' 'Add the fish pieces, add curry leaves and sprinkle asafetida from the top.' 'Cook for 20- 25 minutes.' 'Serve with rice.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West Bengal",
      Rasas: "Amla, Katu",
    },
    {
      idx: 5,
      Recipe_ID: 1080,
      Cuisine: "Indian",
      Recipe_Name: "Rasgulla And/Or Rasmalai",
      Description:
        "I haven't tried this recipe yet, but it sounds delightful. A rasgulla is a cottage cheese ball of sorts, that is boiled in a sugar syrup and served plain with the syrup. The Rasmalai is a rasgulla that is served with a milk sauce with pistachios. YUMMMM! Can't wait to try it! This recipe seems to have a lot of steps, but the last five are ONLY if you are doing the Rasmalai version",
      Image_URLs: "[]",
      Keywords: "['Indian', '< 4 Hours']",
      Ingredient_Quantities: "['1' '3' '3 1⁄2' '1' '1' '1' '3' '1⁄2' '2' '2']",
      Ingredient_Names:
        "['milk', 'lemon juice', 'water', 'sugar', 'cardamom powder', 'milk', 'cardamom', 'pistachios', 'saffron']",
      Calories: "131.2",
      Fat_g: "4.7",
      Saturated_Fat_g: "2.6",
      Cholesterol_mg: "15.9",
      Sodium_mg: "57.7",
      Carbohydrates_g: 19.2,
      Fiber_g: "0.1",
      Sugar_g: 13.5,
      Protein_g: 4,
      Instructions:
        "['FOR RASGULLA:' 'Take a heavy bottomed vessel and boil milk. Once its boiled, slowly add the lemon juice and you will find that the milk will curdle and the whey will separate. The whey will become clear which is an indication that the milk has curdled completely. Immediately add about 10-12 ice cubes and turn off flame. Leave aside for 3-4 minutes.' 'Strain the whey and add the chenna to a damp cheese cloth or a light cotton cloth. Gather the four corners of the cloth and twist it gently and rinse under cold water to remove the sourness of the lemon juice. Tie the ends and hang it at a height and allow the whey from the chenna to drain completely. Leave aside for 30 minutes.' 'Remove the chenna onto a wide plate. Now knead it gently for 7 minutes till there is no trace of moisture and is absolutely soft on touch. This is a very crucial step in the process of rasgulla making.' 'While you are kneading the chenna, prepare the sugar syrup. Place a pressure cooker on the stove and add water and sugar and allow the sugar to dissolve. Bring it to a rolling boil. Add a pinch of cardamom pwd.' 'While the sugar syrup is cooking, make small smooth balls of the kneaded chenna. Ensure there are no cracks on the balls. Slowly add the chenna balls to the boiling sugar syrup. Place lid and pressure cook upto 1 whistle and continue to cook for another 4 minutes.' 'Turn off heat. Once the pressure is off, remove the lid. The balls will double in size and become light and springy on touch. If you feel that the balls are not cooked yet, place lid and cook for another 5 minutes without the whistle at medium heat.' 'Remove onto a serving dish, bring to room temp, refrigerate and serve chilled along with sugar syrup at room temp OR proceed to prepare rasmalai.' 'FOR RASMALAI:' 'Take a heavy bottomed vessel and add milk. Bring to a boil. Reduce to medium flame and go on stirring on a constant basis for a good 30 minutes.' 'Add the sugar syrup and continue to cook for another 20 minutes. Add the cardamom pwd, pistachios and saffron and combine. Boil for another 5 minutes.' 'While the milk-sugar mixture is boiling, work on the rasagullas. Gently squeeze the rasgullas with a flat ladle such that it forms a patty shape and the syrup is drained out.' 'Add the flattened rasgullas into the thickened milk and cook on low flame for 5 minutes. They will absorb the sweet syrup and Rasmalai is ready. Turn off heat and cool.' 'Refrigerate and serve chilled.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West Bengal",
      Rasas: "Madhura, Amla",
    },
    {
      idx: 6,
      Recipe_ID: 464,
      Cuisine: "Indian",
      Recipe_Name: "Fish Curry/Chettinad Fish Curry",
      Description:
        "Spicy aromatic curry that goes well with plain boiled rice. From the authentic Sounth-Indian Kitchen.",
      Image_URLs: "[]",
      Keywords: "['Asian', 'Indian', 'Spicy', '< 60 Mins', 'Small Appliance']",
      Ingredient_Quantities:
        "['4 -6' '2' '2' '2' '3 -5' '2' '2' '1' '1' '1⁄2' '4' '1⁄2' None]",
      Ingredient_Names:
        "['tamarind extract', 'onions', 'tomatoes', 'garlic', 'red chili powder', 'coriander powder', 'fennel seed', 'ground fenugreek', 'turmeric powder', 'coconut milk', 'salt']",
      Calories: "1125.9",
      Fat_g: "44.8",
      Saturated_Fat_g: "16.0",
      Cholesterol_mg: "198.0",
      Sodium_mg: "471.1",
      Carbohydrates_g: 91.8,
      Fiber_g: "9.6",
      Sugar_g: 47.7,
      Protein_g: 93.3,
      Instructions:
        "['Apply a pinch of salt and turmeric powder to the fillets, mix evenly and keep it aside.' 'In a frying pan, pour 4 tablespoons of oil, and add the fennel seeds and fenugreek. Sauté till aroma (about 1 min). Add onions and garlic. Fry till the onion becomes slight golden brown. Add the tomatoes, red chile powder and coriander powder and saute it for 2 minutes, till the tomatoes are pulpy.' 'At this point, add 3 cups of water. (The amount of water depends on the density of gravy needed). Now add the tamarind extract, and let this mixture boil on low flame for about 10 minutes.' 'Add the coconut milk and continue in low flame for another 5 minutes. Now the mixture would have reduced considerably and will be quite thick. Add some more water, if you want.' \"Add the fish pieces and some salt (keep in mind that you have already added salt to the fish) as required . The fish will cook very quickly, in a matter of five minutes. Don't overcook the fish, as they may break when served.\" 'Serve it hot with rice. Note: The more thicker, the more better. It gets thicker as time goes by.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West Bengal",
      Rasas: "Amla, Lavana, Katu",
    },
    {
      idx: 7,
      Recipe_ID: 81,
      Cuisine: "Indian",
      Recipe_Name: "West Pumpkin Soup",
      Description:
        "This is a rich, subtle soup, originally from The West Indies Cookbook by Connie and Arnold Krochmal.",
      Image_URLs: "['",
      Keywords:
        "['Caribbean', 'Low Protein', 'Low Cholesterol', 'Healthy', 'Weeknight', 'Stove Top', 'Small Appliance', '< 4 Hours']",
      Ingredient_Quantities:
        "['2' '2' '1' '900' '5' '3' '1' '2' '2' '2' '1⁄4' '1']",
      Ingredient_Names:
        "['onions', 'garlic', 'butter', 'pumpkin', 'chicken broth', 'bay leaves', 'celery', 'marjoram', 'parsley', 'chives', 'cinnamon']",
      Calories: "186.4",
      Fat_g: "11.0",
      Saturated_Fat_g: "6.4",
      Cholesterol_mg: "31.5",
      Sodium_mg: "674.9",
      Carbohydrates_g: 16.8,
      Fiber_g: "1.8",
      Sugar_g: 4.4,
      Protein_g: 7.2,
      Instructions:
        "['Peel and chop the onions, and peel and mince the garlic.' 'Brown the onions in the butter, and stir in the garlic.' 'Add the pumpkin and broth and bring to a simmer.' 'Add the bay leaves, celery in large chunks, marjoram, parsley and chives.' 'Simmer until tender, about 45 minutes.' 'Remove the pumpkin pieces and set aside.' 'Press everything else through a strainer, and discard all solids.' 'Puree the pumpkin and return it to the soup.' 'Add the cinnamon and cream.' 'Reheat and serve.' 'If you already have pureed cooked pumpkin, simmer the seasonings in the broth for 30 minutes, then strain it as described above.' 'Add the pumpkin and simmer for 5 to 10 minutes more before adding the cinnamon and cream.' 'Use 3 cups pureed pumpkin.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 9,
      Recipe_ID: 664,
      Cuisine: "Indian",
      Recipe_Name: "Broccoli With - Yogurt",
      Description:
        "This is an extra simple, slightly daring, very tasty addition for a standard table vegetable. I believe that it originated with Jamie Oliver. The yogurt mixture keeps well, and is then available to enliven broccoli even in an everyday meal.",
      Image_URLs: "['",
      Keywords: "['Asian', 'Indian', '< 15 Mins', 'Easy']",
      Ingredient_Quantities: "['2' '1' '2' '2' '5' '1' '1']",
      Ingredient_Names:
        "['broccoli', 'extra virgin olive oil', 'cumin seeds', 'fennel seeds', 'cardamom pods', 'plain yogurt', 'lemon']",
      Calories: "104.8",
      Fat_g: "4.5",
      Saturated_Fat_g: "1.2",
      Cholesterol_mg: "5.3",
      Sodium_mg: "71.1",
      Carbohydrates_g: 14.5,
      Fiber_g: "5.1",
      Sugar_g: 4.5,
      Protein_g: 6.1,
      Instructions:
        "['Wash the broccoli, and break it into its florets, and cook 4 to 5 minutes at the most in salted water. Drain.' 'Heat oil in a skillet, and add the drained broccoli.' 'Meanwhile, in a small skillet, toast the cumin, fennel and cardamom until fragrant, about 3 to 4 minutes, and then grind them in a mortar and pestle.' 'Stir most of the spice mixture into the yogurt with the juice of the lemon.' 'Drizzel the spiced yogurt over the broccoli, and garnish with remaining spice mixture and some zest of the lemon.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Pitta",
      Region: "West",
      Rasas: "Amla",
    },
    {
      idx: 11,
      Recipe_ID: 344,
      Cuisine: "Indian",
      Recipe_Name: "West Rum Stew Recipe",
      Description:
        "This is a savory stew that contains dark rum--great for a cold night. Make it and curl up by the fire and enjoy.",
      Image_URLs: "[]",
      Keywords:
        "['Vegetable', 'Meat', 'Winter', 'Beginner Cook', '< 4 Hours', 'Easy']",
      Ingredient_Quantities:
        "['4' '1' '2' '2' '1' '1' '1' '1' '1' '2' '1' '1⁄3' '1' '1' '1⁄3' '1⁄4']",
      Ingredient_Names:
        "['onions', 'bay leaf', 'fresh garlic', 'fresh ground black pepper', 'sugar', 'green pepper', 'fresh tomatoes', 'water', 'tomato paste', 'Tabasco sauce', \"Meyer's dark rum\"]",
      Calories: "370.2",
      Fat_g: "22.1",
      Saturated_Fat_g: "8.9",
      Cholesterol_mg: "76.0",
      Sodium_mg: "159.4",
      Carbohydrates_g: 16.4,
      Fiber_g: "2.8",
      Sugar_g: 8.1,
      Protein_g: 22.8,
      Instructions:
        "['In a large casserole place all ingredients in layers.' 'Combine sauce ingredients.' 'Pour mixture on ingredients in pan; cover and heat in 325°F oven for 1 hour to 1-1/2 hours or until meat is done and veggies are soft.' 'Just before serving or storing add and mix in olives and rum.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 12,
      Recipe_ID: 919,
      Cuisine: "Indian",
      Recipe_Name: "West - Channa Wrap",
      Description:
        "This recipe comes from Kim O'Donnel's \"The Meat Lovers Meatless Cookbook\" and it is so good!",
      Image_URLs: "['",
      Keywords:
        "['Lunch/Snacks', 'Beans', 'Low Protein', 'Low Cholesterol', '< 4 Hours']",
      Ingredient_Quantities:
        "['3' '2' '5' '1⁄2' None '3' '1' '1⁄4' '1⁄4' '1' '2' None None None None]",
      Ingredient_Names:
        "['onions', 'garlic cloves', 'chili pepper', 'fresh ginger', 'curry powder', 'ground cumin', 'cayenne', 'ground turmeric', 'salt', 'chickpeas', 'whole wheat tortilla', 'red onion', 'cucumber']",
      Calories: "200.6",
      Fat_g: "6.8",
      Saturated_Fat_g: "0.9",
      Cholesterol_mg: "0.0",
      Sodium_mg: "612.5",
      Carbohydrates_g: 30.2,
      Fiber_g: "6.3",
      Sugar_g: 1.9,
      Protein_g: 6.2,
      Instructions:
        "[\"In a deep skillet, heat the oil over medium heat. Add the onions and cook until slightly soft, about 8 minutes. Add the garlic, chili pepper and ginger, cook for about 2 minutes. Add the spices and salt, stir well. You'll end up with a paste.\" \"Add chick peas, plus enough water to barely cover (at least 3 cups). Bring to a lively simmer, then lower heat and cook at a gentle simmer, stirring occasionally until most of the liquid evaporates, 50 to 60 minutes. You're looking for very soft chick peas with a thick gravy, not soup.\" 'Tast for salt and season accordingly.' 'Place a few tablespoons of channa into warmed tortilla with any or all of the optional add-ons. The channa is also great over rice.' 'Keeps well in an airtight container in the fridge for at least 5 days.' \"NOTE: recipe wouldn't take 2 x 1 inch piece of ginger, or 8 tortillas, but those are the amounts.\"]",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Lavana, Katu",
    },
    {
      idx: 15,
      Recipe_ID: 659,
      Cuisine: "Indian",
      Recipe_Name: "American Sunflower Seed Cakes",
      Description:
        "Make and share this American Indian Sunflower Seed Cakes recipe from Food.com.",
      Image_URLs: "['",
      Keywords: "['Fruit', 'Nuts', 'Native American', '< 4 Hours', 'Easy']",
      Ingredient_Quantities: "['2 1⁄2' '3' '6' '3' '1⁄2']",
      Ingredient_Names:
        "['sunflower seeds', 'water', 'cornmeal', 'maple syrup']",
      Calories: "221.9",
      Fat_g: "19.4",
      Saturated_Fat_g: "2.0",
      Cholesterol_mg: "0.0",
      Sodium_mg: "5.1",
      Carbohydrates_g: 9.7,
      Fiber_g: "2.2",
      Sugar_g: 3,
      Protein_g: 5.1,
      Instructions:
        "['Simmer the seeds in the water, covered, for 1 hour. Drain & grind the seeds when done.' 'Mix the syrup & cornmeal, 1 tablespoon at a time, into the ground seeds, making a stiff dough. Shape into 3 inch flat cakes, about 15 cakes.' 'Fry the cakes in hot oil on both sides. Drain on paper towels & serve hot.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Pitta",
      Region: "West",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 17,
      Recipe_ID: 720,
      Cuisine: "Indian",
      Recipe_Name: "Tuna Pita Pockets With An Twist !!",
      Description:
        "I originally found this recipe in a Indian cookbook by Shehzad Hussain but this version has a few modifications to suit my family's tastes. It serves as a quick and light Dinner/snack. For a truly Indian twist,you can substitute tzatziki sauce with freshly prepared Cucumber Raita.",
      Image_URLs: "['",
      Keywords:
        "['Asian', 'Indian', '< 30 Mins', 'Beginner Cook', 'Easy', 'Inexpensive']",
      Ingredient_Quantities:
        "['1' '1' '1⁄4' '1⁄2' '1⁄2' '1⁄2' '1⁄4' None '4' '1' '2' '2' '1⁄2' '3' None None]",
      Ingredient_Names:
        "['yellow onion', 'cumin seed', 'ground cumin', 'ground coriander', 'chili powder', 'garam masala', 'salt', 'garlic cloves', 'fresh ginger', 'green chilies', 'tuna in water', 'fresh coriander']",
      Calories: "162.0",
      Fat_g: "3.2",
      Saturated_Fat_g: "0.8",
      Cholesterol_mg: "40.6",
      Sodium_mg: "375.6",
      Carbohydrates_g: 8.4,
      Fiber_g: "1.8",
      Sugar_g: 3.8,
      Protein_g: 24.3,
      Instructions:
        "['Heat oil in a deep pan and stir fry the cumin seeds on medium heat till they begin to splutter.' 'Add the ground corriander,cumin,and red chilli powders and salt.Continue to stir for 2-3 minutes.' 'Next,add the garlic,onions,and pepper.Fry,stirring occassionally until the onion has browned.' 'Add tuna, green chillies and ginger and cook for 5minutes.' 'Stir in the fresh corriander and add garam masala, lemon juice and cook 3-4 minutes till almost dry.' 'To serve,cut warmed pita bread into two, spread the tzatziki sauce evenly and stuff the pita pockets with the tuna filling.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Lavana, Katu",
    },
    {
      idx: 21,
      Recipe_ID: 658,
      Cuisine: "Indian",
      Recipe_Name: "Cornmeal & Berry Dessert",
      Description:
        "Make and share this Indian Cornmeal & Berry Dessert recipe from Food.com.",
      Image_URLs: "['",
      Keywords:
        "['Berries', 'Fruit', 'Native American', 'Sweet', '< 30 Mins', 'Easy']",
      Ingredient_Quantities: "['1' '2' '1⁄4' '1' '2' '1' '3⁄4' '3⁄4' '3']",
      Ingredient_Names:
        "['white cornmeal', 'cold water', 'butter', 'berries', 'nutmeg', 'maple syrup', 'eggs']",
      Calories: "223.5",
      Fat_g: "12.2",
      Saturated_Fat_g: "7.0",
      Cholesterol_mg: "95.5",
      Sodium_mg: "67.2",
      Carbohydrates_g: 26.4,
      Fiber_g: "0.9",
      Sugar_g: 14.7,
      Protein_g: 3.3,
      Instructions:
        "['Soak the cornmeal in the water. Melt the butter in a large pot the add the cornmeal mixture. Heat slowly, stir constantly for 15 minutes, or until thickened.' 'Add the juice, berries, & nutmeg then bring to a boil, stirring constantly. Then add the cream & maple syrup, blending throughly.' 'Add the eggs & remove from the heat, stirring until the mixture stops bubbling. Serve either hot or chilled.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Madhura",
    },
    {
      idx: 23,
      Recipe_ID: 751,
      Cuisine: "Indian",
      Recipe_Name: "Ocean Gazpacho",
      Description:
        "Make and share this Indian Ocean Gazpacho recipe from Food.com.",
      Image_URLs: "[]",
      Keywords:
        "['Asian', 'Indian', 'Low Protein', 'Low Cholesterol', 'Summer', 'Sweet', '< 15 Mins', 'Beginner Cook', 'Small Appliance', 'Easy', 'Inexpensive']",
      Ingredient_Quantities:
        "['1⁄4' '1⁄4' '1⁄4' '1⁄4' '1⁄2' '2' '1' '1⁄4' '1' '2' '4' '1⁄4']",
      Ingredient_Names:
        "['chili powder', 'ginger', 'garlic', 'green chili pepper', 'sugar', 'yogurt', 'lemon juice', 'mint leaf', 'cucumber', 'yogurt', 'garlic cloves', 'salt']",
      Calories: "104.3",
      Fat_g: "4.4",
      Saturated_Fat_g: "2.8",
      Cholesterol_mg: "16.9",
      Sodium_mg: "209.6",
      Carbohydrates_g: 12.1,
      Fiber_g: "0.7",
      Sugar_g: 8.6,
      Protein_g: 5.5,
      Instructions:
        "['Blend all the ingredients for the mint chutney until it becomes a smooth paste.' 'Blend all the ingredients for the yogurt soup and keep it chilled in a refrigerator.' 'To serve, transfer the yogurt soup into a chilled soup bowl. Garnish with mint chutney and fresh mint leaves.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Madhura, Amla, Lavana, Katu",
    },
    {
      idx: 24,
      Recipe_ID: 416,
      Cuisine: "Indian",
      Recipe_Name: " Macaroni And Cheese",
      Description:
        'Make and share this "indian" Macaroni and Cheese recipe from Food.com.',
      Image_URLs: "[]",
      Keywords:
        "['Cheese', 'High In...', '< 30 Mins', 'Beginner Cook', 'Easy', 'Inexpensive']",
      Ingredient_Quantities: "['1' '32' '2' None]",
      Ingredient_Names: "['elbow macaroni', 'cheese', 'milk']",
      Calories: "1021.7",
      Fat_g: "49.4",
      Saturated_Fat_g: "30.4",
      Cholesterol_mg: "129.8",
      Sodium_mg: "1805.4",
      Carbohydrates_g: 91.8,
      Fiber_g: "3.1",
      Sugar_g: 1.7,
      Protein_g: 51.5,
      Instructions:
        "['first you want to take the block of cheese and cut about 1 1/2 to 2 inches of the cheese. For ease of melting cube into small pieces.' 'Bring water to boil and add macaroni and follow direction according to packaging.' 'When macaroni is done about 8-10 minutes drain.' 'In the same pot heat the milk to a simmer and add the cubed cheese. Takes about 5 minutes to melt. Add the macaroni.' \"If there are still small lumps of cheese that's fine. They should finish melting by the time to eat if not its a nice surprise.\" 'Let stand for about 5 minutes for sauce to thicken. Should be thick and creamy.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha",
      Region: "West",
      Rasas: "Sweet",
    },
    {
      idx: 25,
      Recipe_ID: 833,
      Cuisine: "Indian",
      Recipe_Name: "West Crispy Pork Bits",
      Description:
        "Make and share this West Indian Crispy Pork Bits recipe from Food.com.",
      Image_URLs: "[' ' ' '",
      Keywords:
        "['Meat', 'Caribbean', 'Very Low Carbs', 'High Protein', 'High In...', 'Roast', 'Oven', '< 4 Hours', 'Inexpensive']",
      Ingredient_Quantities:
        "['2' None None '1' '1' '1⁄4' '1⁄2' '1⁄2' '1' '1⁄4' '1⁄2']",
      Ingredient_Names:
        "['pork', 'salt', 'pepper', 'garlic', 'ground allspice', 'nutmeg', 'thyme', 'onion', 'olive oil', 'lime juice']",
      Calories: "538.6",
      Fat_g: "25.8",
      Saturated_Fat_g: "8.3",
      Cholesterol_mg: "195.8",
      Sodium_mg: "178.4",
      Carbohydrates_g: 5.5,
      Fiber_g: "0.5",
      Sugar_g: 1.6,
      Protein_g: 67.5,
      Instructions:
        "['Trim some but not all fat from pork.' 'Cube pork into bite sized pieces.' 'Toss with all the other ingredients EXCEPT for the stock.' 'Cover and marinate, refrigerated, for up to 2 days or cook right away.' 'Preheat oven to 375 degrees.' 'Put the meat in a roasting pan large enough to hold it in one layer (it will shrink considerably, so a close fit is okay).' 'Roast for about 1 hour, shaking and stirring the meat occasionally, until the meat is brown and crisp on all sides.' 'Remove the meat with a slotted spoon.' 'Serve hot or at room temperature or proceed to the next step to make a quick sauce.' 'Pour off all but a tablespoon or two of the fat, leaving any solids and as much nonfatty liquid behind as possible.' 'Put the pan on a burner over high heat, add the stock, and cook, stirring and scraping the bottom of the pan, until the liquid is reduced by about half and all the solids are incorporated.' 'Pour over the pork bits and serve.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Amla, Lavana",
    },
    {
      idx: 26,
      Recipe_ID: 883,
      Cuisine: "Indian",
      Recipe_Name: "Hummus",
      Description:
        "Hummus with an East Indian flair of curry and the spicy accent of Serrano chiles. The flavors blend well together in this recipe. I came up with this version of hummus after tiring of the same ol' flavors they sell in the stores. This is an easy, healthy recipe and can be served as an appetizer, sandwich spread, dip for snacking with veggies, or pita chips, anytime!",
      Image_URLs: "[]",
      Keywords:
        "['Beans', 'European', 'Vegan', 'Spicy', 'Weeknight', 'Mixer', '< 15 Mins', 'Small Appliance', 'Inexpensive']",
      Ingredient_Quantities:
        "['2' '4' '4' '2' '1' '2' '3' '1' '1' '1⁄2' '1⁄4' '1' '1⁄4']",
      Ingredient_Names:
        "['chickpeas', 'tahini', 'lemon juice', 'turmeric', 'curry powder', 'garlic cloves', 'jalapeno chile', 'salt', 'black pepper', 'water', 'golden raisin', 'cilantro']",
      Calories: "234.9",
      Fat_g: "6.6",
      Saturated_Fat_g: "0.9",
      Cholesterol_mg: "0.0",
      Sodium_mg: "820.4",
      Carbohydrates_g: 36.9,
      Fiber_g: "7.6",
      Sugar_g: 0.3,
      Protein_g: 9.1,
      Instructions:
        "['In a food processor, blend chickpeas, tahini, lemon juice, agave, turmeric, curry, garlic, chile, salt, pepper, and water until smooth.' \"Once the hummus is smooth, add the raisins and pulse in the food processor until evenly distributed. *Don't over process the raisins*.\" 'If using raisins, you may want to cut back on the agave. Just use your judgment and personal preference. Same with the chile. I like it spicy, so I use more.' 'If using cilantro, stir in by hand or just sprinkle over the top.' 'You can easily cut this recipe in half.' 'Store in the refrigerator.' 'This is good with celery, carrots, all colors of bell peppers, spread on naan, pita chips, use in sandwich or wrap, etc.' 'This recipe makes approximately 24 (2-tablespoon) servings (3 cups).']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Amla, Lavana, Katu",
    },
    {
      idx: 27,
      Recipe_ID: 885,
      Cuisine: "Indian",
      Recipe_Name: "Indiana Martini",
      Description: "Make and share this Indiana Martini recipe from Food.com.",
      Image_URLs: "[]",
      Keywords: "['< 15 Mins', 'Easy']",
      Ingredient_Quantities: "['1 1⁄4' '1⁄4' '3' '1']",
      Ingredient_Names: "['triple sec', 'cherries']",
      Calories: "38.3",
      Fat_g: "0.0",
      Saturated_Fat_g: "0.0",
      Cholesterol_mg: "0.0",
      Sodium_mg: "7.7",
      Carbohydrates_g: 9.7,
      Fiber_g: "0.1",
      Sugar_g: 8.5,
      Protein_g: 0.1,
      Instructions:
        "['Shake, strain and serve up in a martini glass. Garnish with a cherry.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 31,
      Recipe_ID: 555,
      Cuisine: "Indian",
      Recipe_Name: "Edible Corn",
      Description:
        "Make and share this Edible Indian Corn (Fun Kids Recipe) recipe from Food.com.",
      Image_URLs: "[]",
      Keywords:
        "['Lunch/Snacks', 'Low Protein', 'Toddler Friendly', 'Healthy', 'Kid Friendly', 'Thanksgiving', 'Halloween', '< 30 Mins', 'Beginner Cook', 'Easy']",
      Ingredient_Quantities: "['4' '4' '5' '1 1⁄3' None None]",
      Ingredient_Names: "['butter', 'mini marshmallows']",
      Calories: "143.3",
      Fat_g: "3.4",
      Saturated_Fat_g: "2.0",
      Cholesterol_mg: "8.1",
      Sodium_mg: "88.5",
      Carbohydrates_g: 29.4,
      Fiber_g: "2.2",
      Sugar_g: 8.4,
      Protein_g: 1.2,
      Instructions:
        "['In a large pot, melt butter and mini marshmallows over low heat (about 5 minutes). You can also do this in a large bowl in the microwave, checking and stirring every couple minutes.' 'Remove the mixture from the stove and use a wooden spoon to stir in puffed corn cereal and diced dried fruit. Allow the mixture to cool for about 10 minutes.' 'Using buttered hands, shape each treat by pressing 1/3 cup of the mixture around a Popsicle stick. Add fruit leather husks to the bottom of the ear, slightly moistening them to help them stick if needed.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Madhura",
    },
    {
      idx: 32,
      Recipe_ID: 589,
      Cuisine: "Indian",
      Recipe_Name: "Shuck Bread",
      Description:
        "Individual servings of soft bread served in corn husks. Taken from the Country Living Magazine. Note: cooking time includes the time to soak the corn husks.",
      Image_URLs: "[]",
      Keywords:
        "['Low Cholesterol', 'Healthy', 'Thanksgiving', '< 4 Hours', 'Easy', 'Inexpensive']",
      Ingredient_Quantities: "['12' '2' '1' '1' '1' '1⁄2' '1⁄4']",
      Ingredient_Names:
        "['yellow cornmeal', 'brown sugar', 'ground cinnamon', 'baking powder', 'salt', 'cayenne pepper']",
      Calories: "78.8",
      Fat_g: "0.7",
      Saturated_Fat_g: "0.1",
      Cholesterol_mg: "0.0",
      Sodium_mg: "134.8",
      Carbohydrates_g: 17,
      Fiber_g: "1.6",
      Sugar_g: 1.2,
      Protein_g: 1.7,
      Instructions:
        "['Soak corn husks (if dried) in water until softened - about 1 hour.' 'Blot dry and tear off 24 quarter-inch strips from the husks and set them aside (they will be used for ties).' 'Stir together the cornmeal, sugar, cinnamon, baking powder, salt and cayenne pepper with 1 1/2 cups boiling water until a soft dough forms.' 'Pat the dough into 1 by 3 inch logs using about 2 1/2 teaspoons dough per log.' 'Wrap each log with the larger corn husk pieces and tie the ends, to form a packet, with the reserved strips.' 'Fill a large saucepan halfway with water and bring to a boil.' 'Add the packets and cook for 15 minutes.' 'Remove and serve while still hot, in the husks, along with a flavored butter (maple perhaps?).' 'Note: if using fresh corn husks, use the tender,innermost layers for the bread and skip the soaking process.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Lavana",
    },
    {
      idx: 35,
      Recipe_ID: 356,
      Cuisine: "Indian",
      Recipe_Name: "Spicy West Pumpkin Soup",
      Description:
        "This is a fabulous recipe from Cooking Light that I tweaked slightly to make a thicker and more chunky soup. It is on the spicy side but not overwhelmingly spicy.",
      Image_URLs: "[]",
      Keywords:
        "['Vegetable', 'Asian', 'Indian', 'Lactose Free', 'Egg Free', 'Free Of...', 'Spicy', '< 60 Mins', 'Stove Top', 'Easy']",
      Ingredient_Quantities:
        "['1 1⁄2' '3' '1' '1' '1⁄2' '2' '1' '1 1⁄2' '2⁄3' '1⁄4' '2' '1⁄4' '2 -3']",
      Ingredient_Names:
        "['olive oil', 'calabaza squash', 'onion', 'celery', 'habanero pepper', 'garlic cloves', 'brown sugar', 'fresh ginger', 'dried thyme', 'sea salt', 'water', 'bay leaves']",
      Calories: "66.4",
      Fat_g: "4.2",
      Saturated_Fat_g: "0.6",
      Cholesterol_mg: "0.0",
      Sodium_mg: "135.4",
      Carbohydrates_g: 7.4,
      Fiber_g: "0.9",
      Sugar_g: 4.5,
      Protein_g: 0.6,
      Instructions:
        "['Heat the oil in a large saucepan over medium-high heat. Add squash, onion, celery, pepper, and garlic; sauté for 5 minutes. Add remaining ingredients; bring to a boil. Cover, reduce heat, and simmer 25 minutes or until tender. Discard bay leaves.' 'Place half of the squash mixture in a blender, and process slightly so that there are still chunks. Pour pureed mixture into a bowl; repeat procedure with remaining squash mixture. Return pureed mixture to pan; cook over medium heat 3 minutes or until heated.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Lavana, Katu",
    },
    {
      idx: 36,
      Recipe_ID: 620,
      Cuisine: "Indian",
      Recipe_Name: "Flavoured Sausage Rolls",
      Description:
        "Make and share this Indian Flavoured Sausage Rolls recipe from Food.com.",
      Image_URLs: "[]",
      Keywords: "['Easy']",
      Ingredient_Quantities:
        "['1' '1' '1' '2' '2' '1' '500' '375' '1⁄2' '2' '5' '1' '2' '1⁄4' '1' '1' None]",
      Ingredient_Names:
        "['onion', 'garlic clove', 'fresh ginger', 'mild curry paste', 'mango chutney', 'minced beef', 'ground sausage', 'fresh coriander', 'frozen puff pastry', 'egg', 'sesame seeds', 'mango chutney', 'fresh coriander', 'fresh coriander']",
      Calories: "180.0",
      Fat_g: "13.0",
      Saturated_Fat_g: "3.7",
      Cholesterol_mg: "18.6",
      Sodium_mg: "145.3",
      Carbohydrates_g: 10.3,
      Fiber_g: "0.4",
      Sugar_g: 0.5,
      Protein_g: 5.3,
      Instructions:
        "['Heat oil in a pan. Add onion and garlic, cook, stirring until onion is soft. Add ginger and curry paste then stir for 1 minute. Remove from heat then transfer to a large bowl. Add chutney, minces, breadcrumbs and coriander. Using your hands mix until combined.' 'Cut pastry sheets in half lengthways. Place equal amounts of mince mixture lengthways down the centre of each pastry piece. Roll-up, lengthways, to enclose filling. Place seam-side down, onto a chopping board. Brush with egg then sprinkle with seeds. Cut each roll into 6 even pieces. Arrange over lightly oiled oven trays.' 'Cook in a hot oven (200C) for about 30 minutes, or until pastry is browned and crisp.' 'To make Dipping Sauce, place all ingredients in a bowl, stir until combined.' 'Serve sausage rolls with Dipping Sauce garnished with fresh coriander.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 40,
      Recipe_ID: 686,
      Cuisine: "Indian",
      Recipe_Name: "Chai Iced Coffee",
      Description:
        "Garam masala is the combination of Indian spices that is so popular in regional cuisines of India and in its famous chai tea. However, we've discovered it's even more delicious in coffee. If your coffee vendor carries Mysore, India's most famous bean, sample it with this wonderful recipe. The 2 hrs cook time is chill time.",
      Image_URLs: "[' ' '",
      Keywords:
        "['Asian', 'Indian', 'Spicy', 'Sweet', 'Beginner Cook', '< 4 Hours', 'Easy']",
      Ingredient_Quantities:
        "['3' '5' '12' '1' '1' '1⁄4' '2' '1' '2' '2' None]",
      Ingredient_Names:
        "['mineral water', 'fresh ginger', 'whole cloves', 'cinnamon stick', 'anise seed', 'ground cardamom', 'whole cardamom pods', 'ground coffee', 'jaggery', 'dark brown sugar', 'buckwheat honey', 'honey']",
      Calories: "86.3",
      Fat_g: "3.4",
      Saturated_Fat_g: "1.5",
      Cholesterol_mg: "6.1",
      Sodium_mg: "42.3",
      Carbohydrates_g: 13.9,
      Fiber_g: "2.3",
      Sugar_g: 9.6,
      Protein_g: 2.5,
      Instructions:
        "['In a saucepan, add ginger, cloves, anise and cardamom to the cups of water.' 'Break the cinnamon stick and add it to the mixture.' 'Heat over medium heat until the water boils, then reduce the heat to a simmer and cook for about 15 minutes.' 'Add the coffee, stir, and let steep, off the heat, for about 5 minutes.' 'Using a fine meshed filter or cheesecloth, pour the coffee through and into a bowl.' 'Pour the strained coffee into a clean saucepan and add the honey, sugar and milk and heat almost to boiling then remove the pan from the heat, pour into a heat-proof pitcher, cool then refrigerate until it is chilled, about 2 hours.' 'To serve, add ice to squat glasses, pour on the chai coffee, and enjoy. Recipes easily doubles.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Madhura, Katu",
    },
    {
      idx: 41,
      Recipe_ID: 689,
      Cuisine: "Indian",
      Recipe_Name: "Appleous 500",
      Description:
        "This healthy curry dish is the perfect high-performance fuel! For a different flavor, substitute fresh mango for the apple. Adapted from Eat, Shrink & Be Merry.",
      Image_URLs: "[' ' '",
      Keywords:
        "['Chicken Thigh & Leg', 'Chicken', 'Poultry', 'Meat', 'Asian', 'Indian', 'Savory', '< 60 Mins', 'Stove Top', 'Easy']",
      Ingredient_Quantities:
        "['12' '1' '1' '2' '1 1⁄2' '1 1⁄2' '1⁄2' '1⁄2' '1' '1⁄4' '1' '1⁄2' '1' '1⁄2' '2' None]",
      Ingredient_Names:
        "['boneless skinless chicken thighs', 'onion', 'red bell pepper', 'garlic', 'curry powder', 'chili powder', 'ground turmeric', 'ground cinnamon', 'light coconut milk', 'mango chutney', 'lemon, zest of', 'salt', 'golden delicious apple', 'frozen green pea', 'fresh cilantro']",
      Calories: "216.8",
      Fat_g: "5.8",
      Saturated_Fat_g: "1.4",
      Cholesterol_mg: "114.5",
      Sodium_mg: "350.6",
      Carbohydrates_g: 11.2,
      Fiber_g: "3.1",
      Sugar_g: 5.5,
      Protein_g: 29.1,
      Instructions:
        "['Spray large, deep skillet with cooking spray and place over medium-high heat; add chicken pieces and cook until lightly until both sides are lightly browned, about two minutes per side. Remove chicken and keep warm.' 'Add onions, red pepper and garlic to the same skillet. Cook and stir until vegetables begin to soften, about three minutes. Add curry powder, chili powder, turmeric and cinnamon. Cook and stir for one more minute. Add coconut milk, mango chutney, lemon zest and salt. Mix well. Stir in chicken pieces and apples. Cover and simmer over low heat for 15 minutes. Add peas and cilantro. Simmer, uncovered, for five more minutes.' 'Serve hot on a bed of basmati rice.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Amla, Lavana, Katu",
    },
    {
      idx: 42,
      Recipe_ID: 711,
      Cuisine: "Indian",
      Recipe_Name: "W. Sonoma Red Lentil Soup",
      Description:
        'This recipe is from the Williams Sonoma "Soup for Supper" cookbook. I think it is exceptionally good. While lentil soup is usually comfort food, this variation makes it a bit exotic, too. The fragrant Indian spices lighten and brighten the simple, homey flavor of the soup. Red lentils have a tendency to break down into a coarse puree as they cook, so if you prefer some texture, omit the blender or food processor step.',
      Image_URLs: "[]",
      Keywords:
        "['Beans', 'Asian', 'Low Cholesterol', 'Healthy', '< 60 Mins', 'Stove Top', 'Small Appliance']",
      Ingredient_Quantities:
        "['1 1⁄2' '3' '1' '2' '2' '2' '1⁄2' '1' '6' '1 1⁄2' '2' None '3']",
      Ingredient_Names:
        "['red lentils', 'unsalted butter', 'yellow onion', 'ground coriander', 'ground cumin', 'fresh ginger', 'ground turmeric', 'cayenne pepper', 'diced tomatoes', 'lemon juice', 'of fresh mint', 'fresh cilantro']",
      Calories: "255.7",
      Fat_g: "7.5",
      Saturated_Fat_g: "3.9",
      Cholesterol_mg: "15.3",
      Sodium_mg: "154.1",
      Carbohydrates_g: 37.3,
      Fiber_g: "7.5",
      Sugar_g: 3.7,
      Protein_g: 13.3,
      Instructions:
        "['Pick over the red lentils and discard any misshapen lentils or stones.' 'Rinse lentils and drain.' 'In a saucepan over medium heat, melt the butter.' 'Add the onion and saute, stirring occasionally, until tender and translucent (8 to 10 minutes).' 'Add the coriander, cumin, ginger, turmeric, and cayenne and stir to mix well.' 'Reduce the heat to low and cook, stirring occasionally, to release the flavors of the spices (2 to 3 minutes).' 'Add the lentils and then gradually add the water or stock, stirring constantly.' 'Bring to a boil over high heat, reduce the heat to low, cover partially, and simmer until the lentils are very soft (30 to 40 minutes).' 'Remove from the heat and let cool slightly.' 'Working in batches, puree the soup in a blender or food processor.' 'Return the soup to a clean saucepan and place over medium heat.' 'Stir in the tomatoes and lemon juice and cook until heated through.' 'Season with salt and black pepper.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Amla, Lavana",
    },
    {
      idx: 43,
      Recipe_ID: 712,
      Cuisine: "Indian",
      Recipe_Name: "Nut Mix",
      Description:
        "How good does this sound? It's from Australian good taste and I plan on making it for Xmas nibblies.",
      Image_URLs: "[]",
      Keywords: "['Asian', 'Australian', 'Indian', '< 30 Mins', 'Easy']",
      Ingredient_Quantities:
        "['100' '160' '100' '145' '1' '1' '2' '2' '2' '2' '1' '1' '1' None '95']",
      Ingredient_Names:
        "['brazil nuts', 'walnut halves', 'cashew nuts', 'ground cumin', 'ground coriander', 'garam masala', 'sweet paprika', 'ground fennel', 'ground turmeric', 'raisins']",
      Calories: "724.8",
      Fat_g: "56.0",
      Saturated_Fat_g: "8.0",
      Cholesterol_mg: "0.0",
      Sodium_mg: "345.1",
      Carbohydrates_g: 49.6,
      Fiber_g: "8.9",
      Sugar_g: 19.1,
      Protein_g: 18.4,
      Instructions:
        "['Preheat oven to 180°C Combine the Brazil nuts, almonds, walnuts, cashews, noodles, egg white, oil, cumin, coriander, garam masala, paprika, fennel and turmeric in a bowl. Season with salt and pepper. Place in a large roasting pan.' 'Bake in oven, stirring every 5 minutes, for 15 minutes or until nuts are toasted and mixture is aromatic. Add raisins and gently toss to combine. Set aside for 30 minutes to cool to room temperature.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Pitta",
      Region: "West",
      Rasas: "Madhura",
    },
    {
      idx: 44,
      Recipe_ID: 774,
      Cuisine: "Indian",
      Recipe_Name: "English Restaurant Mint Sauce",
      Description:
        "savoury cold sweet sauce found in British Indian restaurants, used as an accompaniment. It's very moreish and I experimented for ages to arrive at something that is as good as that found in a restaurant.",
      Image_URLs: "[]",
      Keywords: "['Indian', 'Spicy', '< 15 Mins', 'Easy']",
      Ingredient_Quantities: "['400' '8' '1⁄4' '300' '80' '1' '1']",
      Ingredient_Names:
        "['plain yogurt', 'sugar', 'chili powder', 'milk', 'mint sauce', 'garlic clove', 'fresh ginger']",
      Calories: "143.1",
      Fat_g: "6.0",
      Saturated_Fat_g: "3.8",
      Cholesterol_mg: "23.5",
      Sodium_mg: "85.7",
      Carbohydrates_g: 16.9,
      Fiber_g: "0.1",
      Sugar_g: 13.1,
      Protein_g: 6,
      Instructions:
        "['Mix all well and leave for at least hour to let flavours meld.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Madhura, Katu, Tikta",
    },
    {
      idx: 45,
      Recipe_ID: 727,
      Cuisine: "Indian",
      Recipe_Name: "Authentic Taco Fry Bread",
      Description:
        "My mom snowbirds in Arizona every year and she got this from a lady who makes Indian Tacos to sell at county fairs, etc. It's authentic and, by far, the best Indian Fry Bread I've ever eaten. It's also very soft and easy to work with. It makes enough tacos for 12-15 people, but it's an easy recipe to halve.",
      Image_URLs: "[]",
      Keywords: "['None']",
      Ingredient_Quantities:
        "['1 1⁄2' '3' '1' '1 1⁄2' '1 1⁄2' '3' '1' '1' '12' None]",
      Ingredient_Names:
        "['warm water', 'compressed yeast cakes', 'flour', 'margarine', 'milk', 'eggs', 'sugar', 'salt', 'flour']",
      Calories: "767.0",
      Fat_g: "26.4",
      Saturated_Fat_g: "5.2",
      Cholesterol_mg: "57.1",
      Sodium_mg: "496.5",
      Carbohydrates_g: 115.1,
      Fiber_g: "3.7",
      Sugar_g: 17.1,
      Protein_g: 16.2,
      Instructions:
        "['YEAST MIXTURE: Mix the first 3 ingredients and let rest for 10 minutes.' 'BATTER MIXTURE: In a separate mixing bowl, combine the remaining ingredients except for the 12 cups of flour. Mix well.' 'Add yeast mixture to batter.' \"Add 12 cups of flour. Mix well. Dough does not have to be kneaded, but should be well-mixed and should rest for awhile. I've found that if you let it double in size, it's even softer and easier to work with.\" 'Form into small \"pats,\" depending on the size you're looking for. Roll or stretch until thin (this dough really puffs up when fried). Fry until golden brown and cooked through.' \"Top with your favorite toppings. We top with hamburger, refried beans, shredded lettuce, tomato, salsa, and sour cream. They're also WONDERFUL with honey butter.\" \"If you don't eat them all the first day, you can keep the dough in the fridge and fry it up in the next day or two. Enjoy!\"]",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Lavana",
    },
    {
      idx: 46,
      Recipe_ID: 565,
      Cuisine: "Indian",
      Recipe_Name: "Summer Cocktail",
      Description:
        'From the Platinum Hotel and Spa in Las Vegas. Found the recipe in the Southwest Airlines magazine. I haven\'t tried it but allegedly it "tastes like chilled apple cider mixed with pumpkin pie spices...crisp and refreshing." Can use spiced cider mix in place of the mulling spices.',
      Image_URLs: "['",
      Keywords: "['Summer', '< 15 Mins']",
      Ingredient_Quantities: "[None '1⁄4' None '2' '2' '1' '3']",
      Ingredient_Names:
        "['lemon wedge', 'spiced rum', 'citrus-infused vodka', 'spiced apple cider']",
      Calories: "197.5",
      Fat_g: "0.0",
      Saturated_Fat_g: "0.0",
      Cholesterol_mg: "0.0",
      Sodium_mg: "0.8",
      Carbohydrates_g: 0,
      Fiber_g: "0.0",
      Sugar_g: 0,
      Protein_g: 0,
      Instructions:
        "['Pour mulling spices/spiced cider mix into a saucer. Run the lemon wedge around the rim of a chilled martini glass to moisten. Turn the class upside down, rotate its rim through the spices, then turn the glass right-side up.' 'Twist the orange spiral over the glass to release the oils from the orange skin, set the spiral aside, then add the bitters.' 'In a shaker half-filled with cracked ice; combine the rum, vodka and cider. Shake well and strain into the martini galss.' 'Garnish the glass with the orange spiral.' 'If desired add a light squeeze from the lemon wedge.' 'Makes one 6-ounce Indian Summer.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Amla, Katu",
    },
    {
      idx: 47,
      Recipe_ID: 746,
      Cuisine: "Indian",
      Recipe_Name: "Green Tea With Chai Spices",
      Description:
        "Make and share this Green Tea With Indian Chai Spices recipe from Food.com.",
      Image_URLs: "[]",
      Keywords: "['< 15 Mins']",
      Ingredient_Quantities: "['4' '4' '4' '6' '2' '1' '4' '1']",
      Ingredient_Names:
        "['white cardamom pods', 'allspice berries', 'whole black peppercorns', 'star anise', 'cinnamon stick', 'boiling water', 'sugar']",
      Calories: "8.1",
      Fat_g: "0.0",
      Saturated_Fat_g: "0.0",
      Cholesterol_mg: "0.0",
      Sodium_mg: "9.5",
      Carbohydrates_g: 2.1,
      Fiber_g: "0.0",
      Sugar_g: 2.1,
      Protein_g: 0,
      Instructions:
        "['Place tea bags into a prewarmed large tea pot; set aside.' 'Crack open the cardamom pods using a mortar and pestle.' 'Discard the empty pods, but keep the tiny black seeds; add the remaining spices to the mortar and crush all into medium-size pieces.' 'Put the spices into a 4 cup heatproof measuring cup and add the boiling water; stir to mix, then let the spices infuse for 2 minutes.' 'Quickly pour the infusion into the teapot, straining carefully to prevent the spices from going into the teapot.' 'Steep the tea in the spice infusion for 2 minutes.' 'Add sugar to the teapot and stir to dissolve; strain the brewed tea into teacups and serve immediately.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 48,
      Recipe_ID: 532,
      Cuisine: "Indian",
      Recipe_Name: "Corn Pudding With Bacon And Chives",
      Description:
        "Make and share this Indian Corn Pudding With Bacon and Chives recipe from Food.com.",
      Image_URLs: "[]",
      Keywords:
        "['Vegetable', 'Native American', 'Healthy', 'Summer', '< 60 Mins', 'Inexpensive']",
      Ingredient_Quantities:
        "[None '2' '1' '1⁄4' '1⁄4' '1⁄4' '1⁄4' '4' '3' '1 1⁄2' '1⁄3' '1' '3']",
      Ingredient_Names:
        "['yellow cornmeal', 'onion', 'salt', 'garlic powder', 'black pepper', 'Canadian bacon', 'fresh corn kernels', 'yellow cornmeal', 'egg', 'fresh chives']",
      Calories: "140.3",
      Fat_g: "4.1",
      Saturated_Fat_g: "1.5",
      Cholesterol_mg: "38.7",
      Sodium_mg: "326.7",
      Carbohydrates_g: 19.9,
      Fiber_g: "2.3",
      Sugar_g: 5.2,
      Protein_g: 8,
      Instructions:
        "['Preheat oven to 350°.' 'Coat a 1 1/2-quart baking dish with cooking spray, and sprinkle with 2 teaspoons cornmeal.' 'Place a large nonstick skillet coated with cooking spray over medium-high heat until hot. Add onion and next 5 ingredients (onion through bacon), and saute 3 minutes or until tender.' 'Stir in corn kernels and 1 cup milk. Reduce heat to low; cover and cook 10 minutes, stirring occasionally. Add 1/3 cup cornmeal, stirring with a whisk.' 'Combine 1/2 cup milk and egg; stir well with a whisk. Add to cornmeal mixture in skillet; stir well. Stir in chives.' 'Spoon mixture into prepared dish. Bake pudding at 350° for 30 minutes or until lightly browned and set. Let stand for 15 minutes.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Lavana",
    },
    {
      idx: 52,
      Recipe_ID: 596,
      Cuisine: "Indian",
      Recipe_Name: "Mini Mince Burgers",
      Description:
        'Ishrat made this on the UK tv show,"Come Dine with Me." I made these for Super Bowl appetizers and we all thought they were wonderful. Ishrat measured everything "by feel," so please feel free to adjust all seasonings very much to taste. I was worried these might be too spicy, but they came out just right for us.',
      Image_URLs: "[]",
      Keywords: "['Meat', 'Asian', 'Indian', '< 30 Mins', 'Easy']",
      Ingredient_Quantities:
        "['1' '2 -3' '1 1⁄2' '1' '1' '1' '2 -3' '1' None '1' '1⁄3' '1' None '1⁄2 - 1' '3']",
      Ingredient_Names:
        "['onion', 'garlic cloves', 'ground lamb', 'ground beef', 'fresh coriander', 'red chili powder', 'garam masala', 'green chilies', 'salt', 'English cucumber', 'red onion', 'salt', 'garam masala', 'fresh coriander leaves']",
      Calories: "413.4",
      Fat_g: "32.1",
      Saturated_Fat_g: "13.9",
      Cholesterol_mg: "99.3",
      Sodium_mg: "555.3",
      Carbohydrates_g: 6.9,
      Fiber_g: "1.2",
      Sugar_g: 2.9,
      Protein_g: 23.6,
      Instructions:
        "['Combine all the ingredients in a large bowl and mix using hands until well blended.' 'Shape the mixture into about 15 small burgers and chill until ready to cook.' \"Grill or pan fry using very little oil on a med/low heat so meat cooks through and doesn't just burn on outside, until burgers are done to your liking (I cooked about 10 minutes).\" 'For the dip, prepare no more than 1 hour before serving (or it gets watery).' 'Mix together the yogurt, onions, and cucumber, adding seasonings to your taste.' 'Cover and chill until ready to serve, adding the coriander leaves on top at the last minute.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, ",
    },
    {
      idx: 53,
      Recipe_ID: 854,
      Cuisine: "Indian",
      Recipe_Name: "West Soup",
      Description: "Make and share this West Indian Soup recipe from Food.com.",
      Image_URLs: "[]",
      Keywords: "['< 4 Hours']",
      Ingredient_Quantities: "['1⁄2' '1⁄2' '4' '1⁄2' '1⁄2' '1' '3' '1']",
      Ingredient_Names:
        "['half-and-half', 'heavy cream', 'fresh garlic cloves', 'leek', 'onion', 'pumpkin puree', 'olive oil']",
      Calories: "276.0",
      Fat_g: "22.1",
      Saturated_Fat_g: "9.0",
      Cholesterol_mg: "47.3",
      Sodium_mg: "296.5",
      Carbohydrates_g: 13.7,
      Fiber_g: "0.6",
      Sugar_g: 4.5,
      Protein_g: 6.7,
      Instructions:
        "['Roast onions, leeks and garlic with olive oil in a pre-heated oven at 300° F for about 30 minutes.' 'remove and purée.' 'Bring the chicken stock, pumpkin purée and puréed vegetables to a boil.' 'Simmer for 45 minutes.' 'Add half and half and simmer for 30 more minutes; season with salt and pepper.' 'Finish with heavy cream.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 55,
      Recipe_ID: 500,
      Cuisine: "Indian",
      Recipe_Name: "West Massala",
      Description:
        "This is an Island Spice mix that is often used in Trini recipes. Posted in response to a recipe for Trini Doubles.",
      Image_URLs: "[]",
      Keywords:
        "['High Fiber', 'Healthy', 'High In...', 'Spicy', '< 15 Mins', 'Beginner Cook', 'Easy']",
      Ingredient_Quantities: "['6' '1' '2' '1' '1 1⁄2' '2' '1⁄2']",
      Ingredient_Names:
        "['fenugreek seeds', 'fennel seeds', 'mustard seeds', 'cumin seeds', 'turmeric', 'ground habanero chile pepper']",
      Calories: "284.9",
      Fat_g: "15.6",
      Saturated_Fat_g: "0.9",
      Cholesterol_mg: "0.0",
      Sodium_mg: "43.9",
      Carbohydrates_g: 46.6,
      Fiber_g: "31.8",
      Sugar_g: 0.6,
      Protein_g: 13.2,
      Instructions:
        "['Toast all the seeds in a dry skillet, stirring well, until they begin popping.' 'Lower the heat and cook for an additional 5 minutes, taking care not to burn the seeds.' 'Cool the seeds and grind them all together finely in a spice mill or with a mortar and pestle.' 'Add the turmeric and mix well if you wish to make a curry powder. Add the habanero powder for a hotter masala.' 'Store in a tightly closed container in your spice cabinet.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Katu",
    },
  ],
  Dinner: [
    {
      idx: 2,
      Recipe_ID: 285,
      Cuisine: "Indian",
      Recipe_Name: "Rasgulla And/Or Rasmalai",
      Description:
        "Traditional Bengali sweet made from chenna (cottage cheese) balls cooked in sugar syrup. A perfect ending to any meal.",
      Image_URLs: "['https://example.com/rasgulla.jpg']",
      Keywords: "['Bengali', 'Sweet', 'Dessert', 'Chenna']",
      Ingredient_Quantities:
        "['1L' '2' '1' '2' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']",
      Ingredient_Names:
        "['milk', 'lemon juice', 'sugar', 'water', 'cardamom powder', 'rose water', 'pistachios', 'almonds', 'saffron', 'ghee', 'flour', 'baking powder', 'salt', 'vanilla extract', 'cream']",
      Calories: "131.0",
      Fat_g: "2.8",
      Saturated_Fat_g: "1.2",
      Cholesterol_mg: "8.5",
      Sodium_mg: "45.0",
      Carbohydrates_g: 24.5,
      Fiber_g: "0.5",
      Sugar_g: 22.8,
      Protein_g: 4.2,
      Instructions:
        "['Boil milk and add lemon juice to curdle it.' 'Strain the curdled milk to get chenna.' 'Knead chenna for 7 minutes until smooth.' 'Make small balls from the chenna.' 'Cook the balls in sugar syrup for 15-20 minutes.' 'For rasmalai, flatten the balls and cook in thickened milk.' 'Garnish with nuts and serve chilled.']",
      Meal_Category: "Dinner",
      Dosha: "Vata, Kapha",
      Region: "East",
      Rasas: "Madhura",
    },
    {
      idx: 0,
      Recipe_ID: 1019,
      Cuisine: "Indian",
      Recipe_Name: "Boka Dushi",
      Description:
        "Ketjap manis (see my fav recipe #480813), the ancestor of modern ketchup, is a thick, sweet soy sauce; you can substitute equal parts soy sauce and molasses. Sambal oelek is a fiery paste made of red peppers. Look for both in Asian markets. From Cooking Light.",
      Image_URLs: "[]",
      Keywords:
        "['Chicken', 'Poultry', 'Meat', 'Indian', 'Spicy', '< 60 Mins']",
      Ingredient_Quantities:
        "['1⁄4' '1' '1' '2' '1' '1⁄2' '1 1⁄2' None '1⁄3' '3' '1⁄2' '2' '2' '1' '1' '1' '1' '1' '1']",
      Ingredient_Names:
        "['ketjap manis', 'fresh lime juice', 'ground cumin', 'fresh ginger', 'sambal oelek', 'ground turmeric', 'boneless skinless chicken breasts', 'creamy peanut butter', 'tomatoes', 'green onions', 'fresh cilantro', 'fish sauce', 'fresh lime juice', 'fresh ginger', 'honey', 'garlic clove']",
      Calories: "189.3",
      Fat_g: "7.1",
      Saturated_Fat_g: "1.5",
      Cholesterol_mg: "72.6",
      Sodium_mg: "406.2",
      Carbohydrates_g: 4.4,
      Fiber_g: "0.9",
      Sugar_g: 2.4,
      Protein_g: 26.6,
      Instructions:
        "['Combine first 7 ingredients in a large zip-top plastic bag; seal and marinate in refrigerator 30 minutes.' 'Prepare grill.' 'Remove chicken from bag and discard marinade. Thread chicken strips onto 18 (8-inch) skewers (soaked if wooden).' 'Place kebabs on grill rack coated with vegetable oil; grill 2 minutes on each side or until done. Serve with prepared Peanut Sauce.' 'To make the Peanut Sauce: Combine broth and peanut butter in a small saucepan; cook over low heat 5 minutes or until smooth, stirring with a whisk. Pour peanut butter mixture into a bowl; stir in the remaining ingredients. Serve at room temperature.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West Indian",
      Rasas: "Madhura, Amla, Katu",
    },
    {
      idx: 45,
      Recipe_ID: 727,
      Cuisine: "Indian",
      Recipe_Name: "Authentic Taco Fry Bread",
      Description:
        "My mom snowbirds in Arizona every year and she got this from a lady who makes Indian Tacos to sell at county fairs, etc. It's authentic and, by far, the best Indian Fry Bread I've ever eaten. It's also very soft and easy to work with. It makes enough tacos for 12-15 people, but it's an easy recipe to halve.",
      Image_URLs: "[]",
      Keywords: "['None']",
      Ingredient_Quantities:
        "['1 1⁄2' '3' '1' '1 1⁄2' '1 1⁄2' '3' '1' '1' '12' None]",
      Ingredient_Names:
        "['warm water', 'compressed yeast cakes', 'flour', 'margarine', 'milk', 'eggs', 'sugar', 'salt', 'flour']",
      Calories: "767.0",
      Fat_g: "26.4",
      Saturated_Fat_g: "5.2",
      Cholesterol_mg: "57.1",
      Sodium_mg: "496.5",
      Carbohydrates_g: 115.1,
      Fiber_g: "3.7",
      Sugar_g: 17.1,
      Protein_g: 16.2,
      Instructions:
        "['YEAST MIXTURE: Mix the first 3 ingredients and let rest for 10 minutes.' 'BATTER MIXTURE: In a separate mixing bowl, combine the remaining ingredients except for the 12 cups of flour. Mix well.' 'Add yeast mixture to batter.' \"Add 12 cups of flour. Mix well. Dough does not have to be kneaded, but should be well-mixed and should rest for awhile. I've found that if you let it double in size, it's even softer and easier to work with.\" 'Form into small \"pats,\" depending on the size you're looking for. Roll or stretch until thin (this dough really puffs up when fried). Fry until golden brown and cooked through.' \"Top with your favorite toppings. We top with hamburger, refried beans, shredded lettuce, tomato, salsa, and sour cream. They're also WONDERFUL with honey butter.\" \"If you don't eat them all the first day, you can keep the dough in the fridge and fry it up in the next day or two. Enjoy!\"]",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Lavana",
    },
    {
      idx: 46,
      Recipe_ID: 565,
      Cuisine: "Indian",
      Recipe_Name: "Summer Cocktail",
      Description:
        'From the Platinum Hotel and Spa in Las Vegas. Found the recipe in the Southwest Airlines magazine. I haven\'t tried it but allegedly it "tastes like chilled apple cider mixed with pumpkin pie spices...crisp and refreshing." Can use spiced cider mix in place of the mulling spices.',
      Image_URLs: "['",
      Keywords: "['Summer', '< 15 Mins']",
      Ingredient_Quantities: "[None '1⁄4' None '2' '2' '1' '3']",
      Ingredient_Names:
        "['lemon wedge', 'spiced rum', 'citrus-infused vodka', 'spiced apple cider']",
      Calories: "197.5",
      Fat_g: "0.0",
      Saturated_Fat_g: "0.0",
      Cholesterol_mg: "0.0",
      Sodium_mg: "0.8",
      Carbohydrates_g: 0,
      Fiber_g: "0.0",
      Sugar_g: 0,
      Protein_g: 0,
      Instructions:
        "['Pour mulling spices/spiced cider mix into a saucer. Run the lemon wedge around the rim of a chilled martini glass to moisten. Turn the class upside down, rotate its rim through the spices, then turn the glass right-side up.' 'Twist the orange spiral over the glass to release the oils from the orange skin, set the spiral aside, then add the bitters.' 'In a shaker half-filled with cracked ice; combine the rum, vodka and cider. Shake well and strain into the martini galss.' 'Garnish the glass with the orange spiral.' 'If desired add a light squeeze from the lemon wedge.' 'Makes one 6-ounce Indian Summer.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Amla, Katu",
    },
    {
      idx: 47,
      Recipe_ID: 746,
      Cuisine: "Indian",
      Recipe_Name: "Green Tea With Chai Spices",
      Description:
        "Make and share this Green Tea With Indian Chai Spices recipe from Food.com.",
      Image_URLs: "[]",
      Keywords: "['< 15 Mins']",
      Ingredient_Quantities: "['4' '4' '4' '6' '2' '1' '4' '1']",
      Ingredient_Names:
        "['white cardamom pods', 'allspice berries', 'whole black peppercorns', 'star anise', 'cinnamon stick', 'boiling water', 'sugar']",
      Calories: "8.1",
      Fat_g: "0.0",
      Saturated_Fat_g: "0.0",
      Cholesterol_mg: "0.0",
      Sodium_mg: "9.5",
      Carbohydrates_g: 2.1,
      Fiber_g: "0.0",
      Sugar_g: 2.1,
      Protein_g: 0,
      Instructions:
        "['Place tea bags into a prewarmed large tea pot; set aside.' 'Crack open the cardamom pods using a mortar and pestle.' 'Discard the empty pods, but keep the tiny black seeds; add the remaining spices to the mortar and crush all into medium-size pieces.' 'Put the spices into a 4 cup heatproof measuring cup and add the boiling water; stir to mix, then let the spices infuse for 2 minutes.' 'Quickly pour the infusion into the teapot, straining carefully to prevent the spices from going into the teapot.' 'Steep the tea in the spice infusion for 2 minutes.' 'Add sugar to the teapot and stir to dissolve; strain the brewed tea into teacups and serve immediately.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 48,
      Recipe_ID: 532,
      Cuisine: "Indian",
      Recipe_Name: "Corn Pudding With Bacon And Chives",
      Description:
        "Make and share this Indian Corn Pudding With Bacon and Chives recipe from Food.com.",
      Image_URLs: "[]",
      Keywords:
        "['Vegetable', 'Native American', 'Healthy', 'Summer', '< 60 Mins', 'Inexpensive']",
      Ingredient_Quantities:
        "[None '2' '1' '1⁄4' '1⁄4' '1⁄4' '1⁄4' '4' '3' '1 1⁄2' '1⁄3' '1' '3']",
      Ingredient_Names:
        "['yellow cornmeal', 'onion', 'salt', 'garlic powder', 'black pepper', 'Canadian bacon', 'fresh corn kernels', 'yellow cornmeal', 'egg', 'fresh chives']",
      Calories: "140.3",
      Fat_g: "4.1",
      Saturated_Fat_g: "1.5",
      Cholesterol_mg: "38.7",
      Sodium_mg: "326.7",
      Carbohydrates_g: 19.9,
      Fiber_g: "2.3",
      Sugar_g: 5.2,
      Protein_g: 8,
      Instructions:
        "['Preheat oven to 350°.' 'Coat a 1 1/2-quart baking dish with cooking spray, and sprinkle with 2 teaspoons cornmeal.' 'Place a large nonstick skillet coated with cooking spray over medium-high heat until hot. Add onion and next 5 ingredients (onion through bacon), and saute 3 minutes or until tender.' 'Stir in corn kernels and 1 cup milk. Reduce heat to low; cover and cook 10 minutes, stirring occasionally. Add 1/3 cup cornmeal, stirring with a whisk.' 'Combine 1/2 cup milk and egg; stir well with a whisk. Add to cornmeal mixture in skillet; stir well. Stir in chives.' 'Spoon mixture into prepared dish. Bake pudding at 350° for 30 minutes or until lightly browned and set. Let stand for 15 minutes.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Lavana",
    },
    {
      idx: 52,
      Recipe_ID: 596,
      Cuisine: "Indian",
      Recipe_Name: "Mini Mince Burgers",
      Description:
        'Ishrat made this on the UK tv show,"Come Dine with Me." I made these for Super Bowl appetizers and we all thought they were wonderful. Ishrat measured everything "by feel," so please feel free to adjust all seasonings very much to taste. I was worried these might be too spicy, but they came out just right for us.',
      Image_URLs: "[]",
      Keywords: "['Meat', 'Asian', 'Indian', '< 30 Mins', 'Easy']",
      Ingredient_Quantities:
        "['1' '2 -3' '1 1⁄2' '1' '1' '1' '2 -3' '1' None '1' '1⁄3' '1' None '1⁄2 - 1' '3']",
      Ingredient_Names:
        "['onion', 'garlic cloves', 'ground lamb', 'ground beef', 'fresh coriander', 'red chili powder', 'garam masala', 'green chilies', 'salt', 'English cucumber', 'red onion', 'salt', 'garam masala', 'fresh coriander leaves']",
      Calories: "413.4",
      Fat_g: "32.1",
      Saturated_Fat_g: "13.9",
      Cholesterol_mg: "99.3",
      Sodium_mg: "555.3",
      Carbohydrates_g: 6.9,
      Fiber_g: "1.2",
      Sugar_g: 2.9,
      Protein_g: 23.6,
      Instructions:
        "['Combine all the ingredients in a large bowl and mix using hands until well blended.' 'Shape the mixture into about 15 small burgers and chill until ready to cook.' \"Grill or pan fry using very little oil on a med/low heat so meat cooks through and doesn't just burn on outside, until burgers are done to your liking (I cooked about 10 minutes).\" 'For the dip, prepare no more than 1 hour before serving (or it gets watery).' 'Mix together the yogurt, onions, and cucumber, adding seasonings to your taste.' 'Cover and chill until ready to serve, adding the coriander leaves on top at the last minute.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, ",
    },
    {
      idx: 53,
      Recipe_ID: 854,
      Cuisine: "Indian",
      Recipe_Name: "West Soup",
      Description: "Make and share this West Indian Soup recipe from Food.com.",
      Image_URLs: "[]",
      Keywords: "['< 4 Hours']",
      Ingredient_Quantities: "['1⁄2' '1⁄2' '4' '1⁄2' '1⁄2' '1' '3' '1']",
      Ingredient_Names:
        "['half-and-half', 'heavy cream', 'fresh garlic cloves', 'leek', 'onion', 'pumpkin puree', 'olive oil']",
      Calories: "276.0",
      Fat_g: "22.1",
      Saturated_Fat_g: "9.0",
      Cholesterol_mg: "47.3",
      Sodium_mg: "296.5",
      Carbohydrates_g: 13.7,
      Fiber_g: "0.6",
      Sugar_g: 4.5,
      Protein_g: 6.7,
      Instructions:
        "['Roast onions, leeks and garlic with olive oil in a pre-heated oven at 300° F for about 30 minutes.' 'remove and purée.' 'Bring the chicken stock, pumpkin purée and puréed vegetables to a boil.' 'Simmer for 45 minutes.' 'Add half and half and simmer for 30 more minutes; season with salt and pepper.' 'Finish with heavy cream.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Kapha, Vata",
      Region: "West",
      Rasas: "Sweet, Sour",
    },
    {
      idx: 55,
      Recipe_ID: 500,
      Cuisine: "Indian",
      Recipe_Name: "West Massala",
      Description:
        "This is an Island Spice mix that is often used in Trini recipes. Posted in response to a recipe for Trini Doubles.",
      Image_URLs: "[]",
      Keywords:
        "['High Fiber', 'Healthy', 'High In...', 'Spicy', '< 15 Mins', 'Beginner Cook', 'Easy']",
      Ingredient_Quantities: "['6' '1' '2' '1' '1 1⁄2' '2' '1⁄2']",
      Ingredient_Names:
        "['fenugreek seeds', 'fennel seeds', 'mustard seeds', 'cumin seeds', 'turmeric', 'ground habanero chile pepper']",
      Calories: "284.9",
      Fat_g: "15.6",
      Saturated_Fat_g: "0.9",
      Cholesterol_mg: "0.0",
      Sodium_mg: "43.9",
      Carbohydrates_g: 46.6,
      Fiber_g: "31.8",
      Sugar_g: 0.6,
      Protein_g: 13.2,
      Instructions:
        "['Toast all the seeds in a dry skillet, stirring well, until they begin popping.' 'Lower the heat and cook for an additional 5 minutes, taking care not to burn the seeds.' 'Cool the seeds and grind them all together finely in a spice mill or with a mortar and pestle.' 'Add the turmeric and mix well if you wish to make a curry powder. Add the habanero powder for a hotter masala.' 'Store in a tightly closed container in your spice cabinet.']",
      Meal_Category: "Lunch/Dinner",
      Dosha: "Vata, Kapha",
      Region: "West",
      Rasas: "Katu",
    },
  ],
};

export { SAMPLE_FOOD_DATA };
